# Generated by Django 5.2.7 on 2025-10-25 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map marker', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map marker', max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Office Location',
                'verbose_name_plural': 'Office Locations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in valid format', regex='^[+]?[(]?[0-9]{1,4}[)]?[-\\s.]?[(]?[0-9]{1,4}[)]?[-\\s.]?[0-9]{1,9}$')], verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contacts_co_created_c1a2bf_idx'), models.Index(fields=['status'], name='contacts_co_status_d675ed_idx'), models.Index(fields=['email'], name='contacts_co_email_25f973_idx')],
            },
        ),
    ]
