# Generated by Django 5.2.7 on 2025-10-07 14:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Explain the center on attraction.')),
                ('image', models.ImageField(upload_to='dest_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tour_type', models.CharField(choices=[('adventure', 'Adventure'), ('beach', 'Beach'), ('cultural', 'Cultural'), ('family', 'Family'), ('luxury', 'Luxury'), ('budget', 'Budget'), ('honeymoon', 'Honeymoon'), ('group', 'Group Tour')], default='adventure', max_length=20)),
                ('description', models.TextField()),
                ('travel_guide', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('duration_dates', models.PositiveIntegerField(default=1)),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('available_until', models.DateField(default=django.utils.timezone.now)),
                ('max_participants', models.PositiveIntegerField(default=1)),
                ('main_image', models.ImageField(upload_to='tour_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='destinations.destination')),
                ('tour_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['-created_at'],
            },
        ),
    ]
