# Generated by Django 5.2.7 on 2025-10-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Explain the center on attraction.')),
                ('total_pricing', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('drop_date', models.DateField()),
                ('image', models.ImageField(upload_to='dest_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('travel_guide', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_at_site', models.DateField()),
                ('description', models.TextField(verbose_name='Exploration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='tour_pics')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='destinations.destination')),
            ],
        ),
    ]
