# Generated by Django 5.2.7 on 2025-10-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_tour_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
