# Generated by Django 5.2.7 on 2025-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_tour_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling')], default='USD', help_text='3-letter currency code', max_length=3),
        ),
    ]
